name: Build and Push CatalogueService to Docker Hub

on:
  push:
    branches:
      - main
      - catalogdomain
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src/CatalogService/CatalogService
          file: ./src/CatalogService/CatalogService/Dockerfile
          push: true
          tags: marthevampire/catalogueservice:latest
